### PR TITLE
Edited SearchCommand and fixed compilation errors

### LINKED ISSUE #61: Implement Basic UI

### LINKED ISSUE #71: Implement list all decks method

### LINKED ISSUE #102: change model/ModelManager to add Decks instead of Flashcards

### PR DESCRIPTION
**Pull request by haveaqiupill**
Travis build is still failing cause of checkstyle :cry: 
Import statements need to be in lexicographical order

### CODE REVIEW

File: src/main/java/cardibuddy/model/CardiBuddy.java [hunk 1]
```diff
@@ -52,31 +64,68 @@ public void setFlashcards(List<Flashcard> flashcards) {
...
+     * The deck must not already exist in the cardi buddy.
+     */
+    public void addDeck(Deck d) {
+        decks.add(d);
+    }
+
+    /**
+     * Replaces the given deck {@code target} in the list with {@code editedDeck}.
+     * {@code target} must exist in the cardi buddy.
+     * The deck identity of {@code editedFlashcard} must not be the same as another existing deck in the cardi buddy.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/CardiBuddy.java:92]: should be editedDeck

File: src/main/java/cardibuddy/model/CardiBuddy.java [hunk 2]
```diff
@@ -52,31 +64,68 @@ public void setFlashcards(List<Flashcard> flashcards) {
...
+     * Returns true if a deck with the same identity as {@code deck} exists in cardibuddy.
+     */
+    public boolean hasDeck(Deck deck) {
+        requireNonNull(deck);
+        return decks.contains(deck);
+    }
+
+    /**
+     * Adds a deck to the cardi buddy.
+     * The deck must not already exist in the cardi buddy.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/CardiBuddy.java]: cardibuddy should be one word

File: src/main/java/cardibuddy/model/CardiBuddy.java [hunk 3]
```diff
@@ -39,7 +43,15 @@ public CardiBuddy(ReadOnlyCardiBuddy toBeCopied) {
     //// list overwrite operations
 
     /**
-     * Replaces the contents of the person list with {@code flashcards}.
+     * Replaces the contents of the flashcard list with {@code flashcards}.
+     * {@code flashcards} must not contain duplicate flashcards.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/CardiBuddy.java]: should be decks

File: src/main/java/cardibuddy/model/CardiBuddy.java [hunk 4]
```diff
@@ -23,13 +26,14 @@
...
     {
+        decks = new UniqueDeckList();
         flashcards = new UniqueFlashcardList();
     }
 
     public CardiBuddy() {}
 
     /**
-     * Creates an CardiBuddy using the Flashcards in the {@code toBeCopied}
+     * Creates a CardiBuddy using the Flashcards in the {@code toBeCopied}
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/CardiBuddy.java]: Maybe can replace 'Flashcards' with 'Decks and Flashcards'?

File: src/main/java/cardibuddy/model/CardiBuddy.java [hunk 5]
```diff
@@ -52,31 +64,68 @@ public void setFlashcards(List<Flashcard> flashcards) {
...
 
     /**
-     * Returns true if a person with the same identity as {@code person} exists in the address book.
+     * Removes {@code key} from this {@code CardiBuddy}.
+     * {@code key} must exist in the cardi buddy.
      */
-    public boolean hasFlashcard(Flashcard person) {
-        requireNonNull(person);
-        return flashcards.contains(person);
+    public void removeDeck(Deck key) {
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/CardiBuddy.java]: Sorry for the confusion but I was wondering why the variable name is named key? Is it not just a normal deck being removed?

File: src/main/java/cardibuddy/model/Model.java [hunk 6]
```diff
@@ -78,11 +78,44 @@
      * {@code target} must exist in the address book.
      * The person identity of {@code editedFlashcard} must not be the same as another existing person in the address book.
      */
-    void setDeck(Flashcard target, Flashcard editedFlashcard);
+    void setDeck(Deck target, Deck editedDeck);
+
+    /**
+     * Returns true if a person with the same identity as {@code person} exists in the address book.
+     */
+    boolean hasCard(Flashcard card);
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/Model.java:87]: Sorry about my naming last time. I can change the flashcard methods to hasFlashcard etc. to match the Cardibuddy class if you want.

File: src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java [hunk 7]
```diff
@@ -0,0 +1,31 @@
+package cardibuddy.model.deck;
+
+import cardibuddy.commons.util.StringUtil;
+import cardibuddy.model.flashcard.Flashcard;
+import java.util.List;
+import java.util.function.Predicate;
+
+/**
+ * Tests that a {@code Person}'s {@code Name} matches any of the keywords given.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java]: Person should be Deck. 
I think Name should be Keyword.

File: src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+    private final List<String> keywords;
+
+    public DeckContainsKeywordsPredicate(List<String> keywords) {
+        this.keywords = keywords;
+    }
+
+    @Override
+    public boolean test(Deck deck) {
+        return keywords.stream()
+                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(deck.getTitle().toString(), keyword));
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java:22]: Actually, is it possible to make the title be a 'String' instead of a 'Title' in the Deck Class? Then we won't need to toString() here.

File: src/main/java/cardibuddy/model/deck/UniqueDeckList.java [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+ * @see Deck#isSameDeck(Deck)
+ */
+public class UniqueDeckList implements Iterable<Deck> {
+
+    private final ObservableList<Deck> internalList = FXCollections.observableArrayList();
+    private final ObservableList<Deck> internalUnmodifiableList =
+            FXCollections.unmodifiableObservableList(internalList);
+
+    /**
+     * Returns true if the list contains an equivalent person as the given argument.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/UniqueDeckList.java]: person should be deck

File: src/main/java/cardibuddy/model/deck/UniqueDeckList.java [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+     */
+    public boolean contains(Deck toCheck) {
+        requireNonNull(toCheck);
+        return internalList.stream().anyMatch(toCheck::isSameDeck);
+    }
+
+    /**
+     * Adds a person to the list.
+     * The person must not already exist in the list.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/UniqueDeckList.java]: person should be deck

Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/UniqueDeckList.java]: person should be deck

File: src/main/java/cardibuddy/model/deck/UniqueDeckList.java [hunk 11]
```diff
@@ -0,0 +1,136 @@
...
+        if (contains(toAdd)) {
+            throw new DuplicateDeckException();
+        }
+        internalList.add(toAdd);
+    }
+
+    /**
+     * Replaces the person {@code target} in the list with {@code editedDeck}.
+     * {@code target} must exist in the list.
+     * The person identity of {@code editedDeck} must not be the same as another existing person in the list.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/UniqueDeckList.java]: person should be deck

File: src/main/java/cardibuddy/model/deck/UniqueDeckList.java [hunk 12]
```diff
@@ -0,0 +1,136 @@
...
+        if (!target.isSameDeck(editedDeck) && contains(editedDeck)) {
+            throw new DuplicateDeckException();
+        }
+
+        internalList.set(index, editedDeck);
+    }
+
+    /**
+     * Removes the equivalent person from the list.
+     * The person must exist in the list.
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/UniqueDeckList.java]: person should be deck

File: src/main/java/cardibuddy/model/deck/exceptions/DuplicateDeckException.java [hunk 13]
```diff
@@ -0,0 +1,11 @@
+package cardibuddy.model.deck.exceptions;
+
+/**
+ * Signals that the operation will result in duplicate Decks (Decks are considered duplicates if they have the same
+ * identity).
+ */
+public class DuplicateDeckException extends RuntimeException {
+    public DuplicateDeckException() {
+        super("Operation would result in duplicate flashcards");
```
Comment (phaebaez) [inline src/main/java/cardibuddy/model/deck/exceptions/DuplicateDeckException.java]: flashcards should be decks

File: src/main/java/cardibuddy/ui/MainWindow.java [hunk 14]
```diff
@@ -106,13 +106,13 @@ private void setAccelerator(MenuItem menuItem, KeyCombination keyCombination) {
      * Fills up all the placeholders of this window.
      */
     void fillInnerParts() {
-        personListPanel = new PersonListPanel(logic.getFilteredPersonList());
+        personListPanel = new PersonListPanel(logic.getFilteredFlashcardList());
         personListPanelPlaceholder.getChildren().add(personListPanel.getRoot());
```
Comment (phaebaez) [inline src/main/java/cardibuddy/ui/MainWindow.java]: Not sure if you want to change this since Sigmund is editing MainWindow also but I think the code should be 'getFilteredDeckList()'. For flashcards, I think it would be under the CommandResult section that would call the open method to show all the flashcards?

File: src/main/java/cardibuddy/logic/commands/SearchCommand.java [hunk 15]
```diff
@@ -1,26 +1,45 @@
...
+/**
+ * Finds and lists all decks in cardi buddy whose title contains any of the argument keywords.
+ * Keyword matching is case insensitive.
+ */
 public class SearchCommand extends Command {
 
     public static final String COMMAND_WORD = "search";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all cards whose questions contain any of "
+    public static final String MESSAGE_USAGE = COMMAND_WORD +
```
Comment (airshhlay) [inline src/main/java/cardibuddy/logic/commands/SearchCommand.java]: What if we are searching for cards! (As in search c/CS2105).

File: src/main/java/cardibuddy/ui/MainWindow.java (hunk 14 above)
Comment (sigmund-c) [reply src/main/java/cardibuddy/ui/MainWindow.java]: ps. I'm not changing this part so go ahead and make any changes!

File: src/main/java/cardibuddy/model/Model.java [hunk 16]
```diff
@@ -78,11 +78,44 @@
...
+    void deleteCard(Flashcard target);
+
+    /**
+     * Adds the given person.
+     * {@code person} must not already exist in the address book.
+     */
+    void addCard(Flashcard person);
+
+    /**
+     * Replaces the given person {@code target} with {@code editedFlashcard}.
```
Comment (airshhlay) [inline src/main/java/cardibuddy/model/Model.java]: > Replaces the given person {@code target} with {@code editedFlashcard}

Should change person

File: src/main/java/cardibuddy/model/Model.java [hunk 17]
```diff
@@ -78,11 +78,44 @@
...
+     * {@code target} must exist in the address book.
+     * The person identity of {@code editedFlashcard} must not be the same as another existing person in the address book.
```
Comment (airshhlay) [inline src/main/java/cardibuddy/model/Model.java]: same for this one!

File: src/main/java/cardibuddy/model/ModelManager.java [hunk 18]
```diff
@@ -75,45 +76,62 @@ public Path getCardiBuddyFilePath() {
...
+
+    public boolean hasCard(Flashcard person) {
+        return true;
+    }
+
+    public void deleteCard(Flashcard target) {
+        cardiBuddy.removeFlashcard(target);
+    }
+
+    public void addCard(Flashcard person) {
```
Comment (airshhlay) [inline src/main/java/cardibuddy/model/ModelManager.java]: > public void addCard(Flashcard person) {
gotta change!

File: src/main/java/cardibuddy/model/Model.java (hunk 6 above)
Comment (haveaqiupill) [reply src/main/java/cardibuddy/model/Model.java:87]: up to you!!

File: src/main/java/cardibuddy/model/deck/Deck.java [hunk 19]
```diff
@@ -70,6 +70,15 @@ public boolean equals(Object other) {
                 && otherDeck.getFlashcards().equals(getFlashcards());
     }
 
+    public boolean isSameDeck(Deck otherDeck) {
```
Comment (airshhlay) [inline src/main/java/cardibuddy/model/deck/Deck.java:68]: what's the need for this one! compared to equals(). Are there instances where the deck contents are different but the title same?

File: src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java (hunk 8 above)
Comment (haveaqiupill) [reply src/main/java/cardibuddy/model/deck/DeckContainsKeywordsPredicate.java:22]: Hmmm but in the Person class Name and the other attributes were separate classes

File: src/main/java/cardibuddy/ui/MainWindow.java (hunk 14 above)
Comment (haveaqiupill) [reply src/main/java/cardibuddy/ui/MainWindow.java]: I haven't really changed the UI part cause there are other dependencies (PersonListPanel should be changed to DeckListPanel and it'll take a while!) I'll do it on the next iteration

File: src/main/java/cardibuddy/Main.java [hunk 20]
```diff
@@ -1,7 +1,6 @@
 package cardibuddy;
 
 import javafx.application.Application;
-import seedu.address.MainApp;
```
Comment (airshhlay) [inline src/main/java/cardibuddy/Main.java:4]: `import cardibuddy.MainApp` ?

**Review by airshhlay — CHANGES_REQUESTED** [review]

**Comment by sigmund-c** [comment]
Ok can merge quickly so that we can test it out!

File: src/main/java/cardibuddy/logic/commands/SearchCommand.java (hunk 15 above)
Comment (haveaqiupill) [reply src/main/java/cardibuddy/logic/commands/SearchCommand.java]: I'll implement in the next milestone! Currently I'm implementing for decks only.

File: src/main/java/cardibuddy/model/deck/Deck.java (hunk 19 above)
Comment (haveaqiupill) [reply src/main/java/cardibuddy/model/deck/Deck.java:68]: removed equals!
